TRADUZIDO CODIGO

diff --git a/scripts/get_git b/scripts/get_git
--- a/scripts/get_git
+++ b/scripts/get_git
@@ -1,25 +1,25 @@
 # SPDX-License-Identifier: GPL-2.0
 # Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)
 
-# Handler for git
-# Usage (in package.mk):
-# PKG_URL (mandatory) must point to a git repository (git://... or https://example.com/repo.git)
-# PKG_VERSION (mandatory) must point to a commit SHA, e.g. a1b2c3d
-# PKG_GIT_SHA (optional) full hash of git commit
-# PKG_GIT_CLONE_BRANCH (optional) clone specific branch
-# PKG_GIT_CLONE_SINGLE (optional) clone single branch only (set to yes)
-# PKG_GIT_CLONE_DEPTH (optional) history to clone, must be a number
-# PKG_GIT_SUBMODULE_DEPTH (optional) history of submodules to clone, must be a number
+# Manipulador para git
+# Uso (em package.mk):
+# PKG_URL (obrigatório) deve apontar para um repositório git (git://... ou https://example.com/repo.git)
+# PKG_VERSION (obrigatório) deve apontar para um commit SHA, por exemplo a1b2c3d
+# PKG_GIT_SHA (opcional) hash completo do git commit
+# PKG_GIT_CLONE_BRANCH (opcional) clone branch específico
+# PKG_GIT_CLONE_SINGLE (opcional) clona apenas ramificação única (definido como sim)
+# PKG_GIT_CLONE_DEPTH (opcional) histórico para clonar, deve ser um número
+# PKG_GIT_SUBMODULE_DEPTH (opcional) histórico dos submódulos a clonar, deve ser um número
 
 _get_repo_already_downloaded() {
   if [ -d "${PACKAGE}" ]; then
     (
       cd "${PACKAGE}"
       _get_repo_clean
-      [ -n "$(git ls-remote . | grep -m1 HEAD | awk "/^${PKG_VERSION}/ {print \$1;}")" ] || die "ERROR: ${PACKAGE}: failed to determine git HEAD"
+      [ -n "$(git ls-remote . | grep -m1 HEAD | awk "/^${PKG_VERSION}/ {print \$1;}")" ] || die "ERROR: ${PACKAGE}: falhou ao determinar git HEAD"
       [ "${PKG_URL}" = "$(git remote get-url origin)" ] || die "ERROR: ${PACKAGE}: failed to obtain URL of origin"
       [ -z "${PKG_GIT_CLONE_BRANCH}" ] && exit 0
-      [ "${PKG_GIT_CLONE_BRANCH}" = "$(git branch | grep ^\* | cut -d ' ' -f2)" ] || die "ERROR: ${PACKAGE}: failed to determine current git branch"
+      [ "${PKG_GIT_CLONE_BRANCH}" = "$(git branch | grep ^\* | cut -d ' ' -f2)" ] || die "ERROR: ${PACKAGE}: falhou ao determinar o branch atual do git"
       exit 0
     )
     return
@@ -42,9 +42,9 @@ lock_source_dir "${1}"
 _get_repo_already_downloaded && exit 0
 
 # At this point, we need to download something...
-build_msg "CLR_GET" "GET" "${1} (git)" "indent"
+build_msg "CLR_GET" "GET" "${1} (git)" "recuar"
 
-pkg_lock_status "GETPKG" "${PKG_NAME}" "unpack" "processing package repository..."
+pkg_lock_status "GETPKG" "${PKG_NAME}" "descompactar" "processando repositório de pacotes..."
 
 rm -f "${STAMP_URL}" "${STAMP_SHA}"
 
@@ -58,7 +58,7 @@ if [ -n "${PKG_GIT_CLONE_DEPTH}" ]; then
   if [[ "${PKG_GIT_CLONE_DEPTH}" =~ ^[0-9]+$ ]]; then
     GIT_CLONE_PARAMS="${GIT_CLONE_PARAMS} --depth ${PKG_GIT_CLONE_DEPTH}"
   else
-    die "ERROR: PKG_GIT_CLONE_DEPTH is not a number! (${PKG_GIT_CLONE_DEPTH})"
+    die "ERROR: PKG_GIT_CLONE_DEPTH não é um número! (${PKG_GIT_CLONE_DEPTH})"
   fi
 fi
 
@@ -66,7 +66,7 @@ if [ -n "${PKG_GIT_SUBMODULE_DEPTH}" ]; then
   if [[ "${PKG_GIT_SUBMODULE_DEPTH}" =~ ^[0-9]+$ ]]; then
     GIT_SUBMODULE_PARAMS="${GIT_SUBMODULE_PARAMS} --depth ${PKG_GIT_SUBMODULE_DEPTH}"
   else
-    die "ERROR: PKG_GIT_SUBMODULE_DEPTH is not a number! (${PKG_GIT_SUBMODULE_DEPTH})"
+    die "ERROR: PKG_GIT_SUBMODULE_DEPTH não é um número! (${PKG_GIT_SUBMODULE_DEPTH})"
   fi
 fi
 
@@ -131,5 +131,5 @@ fi
 GIT_SHA="$(git ls-remote "${PACKAGE}" | grep -m1 HEAD | awk '{print $1;}')"
 
 if [ -n "${PKG_GIT_SHA}" -a "${PKG_GIT_SHA}" != "${GIT_SHA}" ]; then
-  build_msg "CLR_WARNING" "WARNING" "Incorrect git hash in repository: got ${GIT_SHA}, wanted ${PKG_GIT_SHA}"
+  build_msg "CLR_WARNING" "AVISO" "Git hash incorreto no repositório: got ${GIT_SHA}, wanted ${PKG_GIT_SHA}"
 fi
