TRADUZIDO CODIGO

diff --git a/scripts/makefile_helper b/scripts/makefile_helper
--- a/scripts/makefile_helper
+++ b/scripts/makefile_helper
@@ -12,8 +12,7 @@ BUILD_BASE=$(PROJECT= DEVICE= ARCH= . config/options "" && echo "${BUILD_BASE}")
 
 if [ -z "${BUILD_BASE}" -o -z "${BUILD_ROOT}" ]; then
   # make sure variables are set before running an rm
-  echo "error: ${0}: both BUILD_BASE and BUILD_ROOT must be set when running \"[clean|distclean]\"; aborting"
-  exit 1
+echo "erro: ${0}: ambos BUILD_BASE e BUILD_ROOT devem ser definidos ao executar \"[clean|distclean]\"; abortando"  exit 1
 fi
 
 # task handling
@@ -25,7 +24,7 @@ case $1 in
     rm -rf "${BUILD_ROOT}/.ccache" "${BUILD_ROOT}/${BUILD_BASE}."*
   ;;
   *)
-    echo "error: ${0}: unsupported option on CLI; aborting"
+    echo "erro: ${0}: opção não suportada na CLI; abortando"
     exit 1
   ;;
 esac
